set(FILES
	Source/Components/BeamComponent.cpp
	Source/Components/BeamComponent.hpp
	Source/Components/SpaceshipComponent.cpp
	Source/Components/SpaceshipComponent.hpp
	Source/Components/TileComponent.cpp
	Source/Components/TileComponent.hpp
	Source/EBuses/TileBus.hpp
)
